project:
  type: website
  output-dir: docs

website:
  title: "Learning Identity an Access Management - Use-Cases"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - authentication.qmd
      - authorization.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
